name: Setup project
description: Sets up the repo code, Node.js, and npm dependencies

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: npm
        registry-url: https://registry.npmjs.org
    - name: Install npm dependencies
      run: npm ci
      shell: bash
